import { useEffect, useState, type FormEvent } from "react";
import type { AccessibleCompany } from "../services/auth";
import { caughtErrorMessage } from "../services/api";
import { companyName, itemsApi, type Category, type Item, type ItemInput } from "../services/items";

const blank: ItemInput = { name: "", display_name: null, code: null, item_type: "goods", description: null, category_id: null, uom_code: "PCS", hsn_sac_code: null, barcode: null, purchase_price: null, selling_price: null, gst_rate: null, track_inventory: false, opening_stock: 0, reorder_level: null, default_warehouse_id: null, image_url: null, notes: null };
const optional = (form: FormData, key: string) => String(form.get(key) ?? "").trim() || null;

export function ItemsPage({ company, mode = "items" }: { company?: AccessibleCompany; mode?: "items" | "categories" }) {
  const companyId = company?.id ?? "";
  const [items, setItems] = useState<Item[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [uoms, setUoms] = useState<string[]>([]); const [editing, setEditing] = useState<Item | null>(null); const [adding, setAdding] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const reload = () => { if (!companyId) return; setItems([]); itemsApi.items(companyId).then(setItems).catch((e: unknown) => setNotice(caughtErrorMessage(e, "Items could not be loaded."))); itemsApi.categories(companyId).then(setCategories).catch((e: unknown) => setNotice(caughtErrorMessage(e, "Categories could not be loaded."))); itemsApi.uoms(companyId).then(setUoms).catch((e: unknown) => setNotice(caughtErrorMessage(e, "Units could not be loaded."))); };
  useEffect(reload, [companyId]);
  if (!company) return <section className="organization-empty"><h1>{mode === "items" ? "Items" : "Item categories"}</h1><p>Select a company first.</p></section>;
  if (mode === "categories") return <Categories companyId={companyId} categories={categories} reload={reload} />;
  async function save(payload: ItemInput) { try { const saved = editing ? await itemsApi.update(companyId, editing.id, payload) : await itemsApi.create(companyId, payload); setItems((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setEditing(null); setAdding(false); setNotice("Item saved."); } catch (e) { setNotice(caughtErrorMessage(e, "Item could not be saved.")); } }
  return <div className="page-stack organization-page party-page"><section className="organization-hero"><div><p className="section-kicker">Inventory masters</p><h1>Items</h1><p>Manage reusable goods and services for {companyName(company)}.</p></div><button className="primary-action" onClick={() => { setAdding(true); setEditing(null); }}>Add item</button></section>{notice && <p className="notice">{notice}</p>}<section className="organization-card administration-card">{(adding || editing) && <ItemForm item={editing} categories={categories} uoms={uoms} onSave={save} onCancel={() => { setAdding(false); setEditing(null); }} />}<div className="party-list">{items.map((item) => <article className="party-row" key={item.id}><div><strong>{item.name}</strong><p>{[item.code, item.item_type, item.category_name, item.uom_code].filter(Boolean).join(" · ")}</p><small>Selling price: {item.selling_price ?? "—"}</small></div><div className="location-actions"><span className={`status-badge ${item.is_active ? "active" : "inactive"}`}>{item.is_active ? "Active" : "Inactive"}</span><button className="secondary-action" onClick={() => { setEditing(item); setAdding(false); }}>Edit</button><button className="secondary-action" onClick={() => itemsApi.status(companyId, item.id, !item.is_active).then(reload).catch((e: unknown) => setNotice(caughtErrorMessage(e, "Status could not be updated.")))}>{item.is_active ? "Deactivate" : "Activate"}</button></div></article>)}</div></section></div>;
}

function ItemForm({ item, categories, uoms, onSave, onCancel }: { item: Item | null; categories: Category[]; uoms: string[]; onSave: (value: ItemInput) => Promise<void>; onCancel: () => void }) {
  const initial = item ?? blank; const [type, setType] = useState(initial.item_type);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void onSave({ ...blank, name: String(form.get("name") ?? "").trim(), code: optional(form, "code"), item_type: type, category_id: optional(form, "category_id"), uom_code: String(form.get("uom_code")), hsn_sac_code: optional(form, "hsn_sac_code"), barcode: optional(form, "barcode"), purchase_price: optional(form, "purchase_price") ? Number(form.get("purchase_price")) : null, selling_price: optional(form, "selling_price") ? Number(form.get("selling_price")) : null, gst_rate: optional(form, "gst_rate") ? Number(form.get("gst_rate")) : null, track_inventory: type === "goods" && form.get("track_inventory") === "on", opening_stock: type === "goods" ? Number(form.get("opening_stock") || 0) : 0, reorder_level: type === "goods" && optional(form, "reorder_level") ? Number(form.get("reorder_level")) : null, image_url: optional(form, "image_url"), description: optional(form, "description"), notes: optional(form, "notes") }); }
  return <form className="inline-form party-form" onSubmit={submit}><h3>{item ? "Edit item" : "New item"}</h3><fieldset><legend>Basic information</legend><label>Name<input name="name" defaultValue={initial.name} required /></label><label>Item code<input name="code" defaultValue={initial.code ?? ""} placeholder="Auto if blank" /></label><label>Type<select value={type} onChange={(event) => setType(event.target.value as "goods" | "service")}><option value="goods">Goods / Stock Item</option><option value="service">Service</option></select></label><label>Category<select name="category_id" defaultValue={initial.category_id ?? ""}><option value="">None</option>{categories.filter((category) => category.is_active).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>UOM<select name="uom_code" defaultValue={initial.uom_code}>{uoms.map((uom) => <option key={uom}>{uom}</option>)}</select></label></fieldset><fieldset><legend>Tax and pricing</legend><label>HSN / SAC<input name="hsn_sac_code" defaultValue={initial.hsn_sac_code ?? ""} /></label><label>GST rate<select name="gst_rate" defaultValue={initial.gst_rate ?? ""}><option value="">Not set</option>{[0, 5, 12, 18, 28].map((rate) => <option key={rate}>{rate}</option>)}</select></label><label>Purchase price<input name="purchase_price" type="number" step="0.01" defaultValue={initial.purchase_price ?? ""} /></label><label>Selling price<input name="selling_price" type="number" step="0.01" defaultValue={initial.selling_price ?? ""} /></label></fieldset>{type === "goods" && <fieldset><legend>Inventory foundation</legend><label><input name="track_inventory" type="checkbox" defaultChecked={initial.track_inventory} /> Track inventory</label><label>Opening stock<input name="opening_stock" type="number" step="0.001" defaultValue={initial.opening_stock} /></label><label>Reorder level<input name="reorder_level" type="number" step="0.001" defaultValue={initial.reorder_level ?? ""} /></label></fieldset>}<fieldset><legend>Barcode, image, notes</legend><label>Barcode<input name="barcode" defaultValue={initial.barcode ?? ""} /></label><label>Image URL<input name="image_url" defaultValue={initial.image_url ?? ""} /></label><label className="full-width">Description<textarea name="description" defaultValue={initial.description ?? ""} /></label><label className="full-width">Notes<textarea name="notes" defaultValue={initial.notes ?? ""} /></label></fieldset><div className="form-actions"><button className="primary-action">Save item</button><button className="secondary-action" type="button" onClick={onCancel}>Cancel</button></div></form>;
}

function Categories({ companyId, categories, reload }: { companyId: string; categories: Category[]; reload: () => void }) { const [name, setName] = useState(""); return <div className="page-stack organization-page party-page"><section className="organization-hero"><div><p className="section-kicker">Inventory masters</p><h1>Item categories</h1></div></section><section className="organization-card administration-card"><form className="inline-form" onSubmit={(event) => { event.preventDefault(); itemsApi.createCategory(companyId, { name, code: null, description: null }).then(() => { setName(""); reload(); }); }}><label>Category name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><button className="primary-action">Add category</button></form><div className="party-list">{categories.map((category) => <article className="party-row" key={category.id}><strong>{category.name}</strong><button className="secondary-action" onClick={() => itemsApi.categoryStatus(companyId, category.id, !category.is_active).then(reload)}>{category.is_active ? "Deactivate" : "Activate"}</button></article>)}</div></section></div>; }
