import { useEffect, useState, type FormEvent } from "react";
import type { AccessibleCompany } from "../services/auth";
import { caughtErrorMessage } from "../services/api";
import { companyName, partiesApi, type Party, type PartyInput } from "../services/parties";

type Role = "customer" | "supplier";
const blank = (role: Role): PartyInput => ({ display_name: "", legal_name: null, code: null, party_type: role, contact_person: null, mobile_number: null, alternate_mobile: null, email: null, address_line1: null, address_line2: null, city: null, state: null, postal_code: null, country: "India", gst_status: "unregistered", gstin: null, pan: null, opening_balance: 0, opening_balance_type: "debit", credit_limit: null, payment_terms_days: null, notes: null });
const value = (item: string | number | null | undefined) => item ?? "";
const nullable = (form: FormData, key: string) => String(form.get(key) ?? "").trim() || null;

export function PartiesPage({ company, role }: { company?: AccessibleCompany; role: Role }) {
  const title = role === "customer" ? "Customers" : "Suppliers";
  const companyId = company?.id;
  const [items, setItems] = useState<Party[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [active, setActive] = useState(""); const [editing, setEditing] = useState<Party | null>(null); const [adding, setAdding] = useState(false); const [notice, setNotice] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  const load = () => { if (!companyId) return; setLoading(true); partiesApi.list(role, companyId, { search: search || undefined, active: active || undefined }).then(setItems).catch((error: unknown) => setNotice({ kind: "error", text: caughtErrorMessage(error, "Party data could not be loaded.") })).finally(() => setLoading(false)); };
  useEffect(() => { setItems([]); setEditing(null); setAdding(false); setNotice(null); setSearch(""); setActive(""); if (!company) { setLoading(false); return; } setLoading(true); partiesApi.list(role, company.id).then(setItems).catch((error: unknown) => setNotice({ kind: "error", text: caughtErrorMessage(error, "Party data could not be loaded.") })).finally(() => setLoading(false)); }, [company?.id, role]);
  if (!company) return <section className="organization-empty"><h1>{title}</h1><p>Select an authorized company to manage its {title.toLowerCase()}.</p></section>;
  async function save(payload: PartyInput) { if (!companyId) return; try { const saved = editing ? await partiesApi.update(role, companyId, editing.id, payload) : await partiesApi.create(role, companyId, payload); setItems((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setEditing(null); setAdding(false); setNotice({ kind: "success", text: `${title.slice(0, -1)} ${editing ? "updated" : "created"}.` }); } catch (error) { setNotice({ kind: "error", text: caughtErrorMessage(error, "Party data could not be updated.") }); } }
  async function toggle(item: Party) { if (!companyId || !window.confirm(`${item.is_active ? "Deactivate" : "Activate"} ${item.display_name}?`)) return; try { const saved = await partiesApi.setStatus(role, companyId, item.id, !item.is_active); setItems((current) => current.map((currentItem) => currentItem.id === saved.id ? saved : currentItem)); setNotice({ kind: "success", text: `${item.display_name} ${saved.is_active ? "activated" : "deactivated"}.` }); } catch (error) { setNotice({ kind: "error", text: caughtErrorMessage(error, "Party status could not be updated.") }); } }
  return <div className="page-stack organization-page party-page"><section className="organization-hero"><div><p className="section-kicker">Business masters</p><h1>{title}</h1><p>Manage {role === "customer" ? "customers for sales and receivables" : "suppliers for purchases and payables"} in {companyName(company)}.</p></div><button className="primary-action" onClick={() => { setAdding(true); setEditing(null); }}>Add {title.slice(0, -1)}</button></section>{notice && <p className={`notice ${notice.kind}`}>{notice.text}</p>}<section className="organization-card administration-card"><div className="admin-toolbar"><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === "Enter" && load()} placeholder={`Search name, code, GSTIN, mobile, or email`} /><label>Status<select value={active} onChange={(event) => { setActive(event.target.value); }}><option value="">All</option><option value="true">Active</option><option value="false">Inactive</option></select></label><button className="secondary-action" onClick={load}>Apply filters</button></div>{(adding || editing) && <PartyForm role={role} party={editing} onSave={save} onCancel={() => { setAdding(false); setEditing(null); }} />}{loading ? <div className="empty-state"><strong>Loading {title.toLowerCase()}…</strong></div> : !items.length ? <div className="empty-state"><strong>No {title.toLowerCase()} found</strong><p>{search || active ? "Try different filters or add a new record." : `Add your first ${title.slice(0, -1).toLowerCase()} to create a reusable business master.`}</p></div> : <div className="party-list">{items.map((item) => <article key={item.id} className="party-row"><div><strong>{item.display_name}</strong><p>{[item.code, item.party_type === "both" ? "Customer & Supplier" : null, item.city, item.state].filter(Boolean).join(" · ")}</p><small>{[item.gstin, item.mobile_number, item.email].filter(Boolean).join(" · ") || "No contact or tax details yet"}</small></div><div className="location-actions"><span className={`status-badge ${item.is_active ? "active" : "inactive"}`}>{item.is_active ? "Active" : "Inactive"}</span><button className="secondary-action" onClick={() => { setEditing(item); setAdding(false); }}>Edit</button><button className="secondary-action" onClick={() => void toggle(item)}>{item.is_active ? "Deactivate" : "Activate"}</button></div></article>)}</div>}</section></div>;
}

function PartyForm({ role, party, onSave, onCancel }: { role: Role; party: Party | null; onSave: (payload: PartyInput) => Promise<void>; onCancel: () => void }) {
  const [saving, setSaving] = useState(false); const initial = party ?? blank(role); const [gstStatus, setGstStatus] = useState(initial.gst_status);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); await onSave({ display_name: String(form.get("display_name") ?? "").trim(), legal_name: nullable(form, "legal_name"), code: nullable(form, "code"), party_type: String(form.get("party_type") ?? role) as PartyInput["party_type"], contact_person: nullable(form, "contact_person"), mobile_number: nullable(form, "mobile_number"), alternate_mobile: nullable(form, "alternate_mobile"), email: nullable(form, "email"), address_line1: nullable(form, "address_line1"), address_line2: nullable(form, "address_line2"), city: nullable(form, "city"), state: nullable(form, "state"), postal_code: nullable(form, "postal_code"), country: nullable(form, "country"), gst_status: String(form.get("gst_status")) as PartyInput["gst_status"], gstin: nullable(form, "gstin"), pan: nullable(form, "pan"), opening_balance: Number(form.get("opening_balance") || 0), opening_balance_type: String(form.get("opening_balance_type")) as "debit" | "credit", credit_limit: nullable(form, "credit_limit") ? Number(form.get("credit_limit")) : null, payment_terms_days: nullable(form, "payment_terms_days") ? Number(form.get("payment_terms_days")) : null, notes: nullable(form, "notes") }); setSaving(false); }
  const field = (name: keyof PartyInput, label: string, type = "text", required = false) => <label>{label}<input name={name} type={type} defaultValue={String(value(initial[name] as string | number | null))} required={required} /></label>;
  const gstinRequired = gstStatus === "registered" || gstStatus === "composition";
  return <form className="inline-form party-form" onSubmit={(event) => void submit(event)}><h3>{party ? `Edit ${role}` : `New ${role}`}</h3><fieldset><legend>Basic information</legend>{field("display_name", "Display name", "text", true)}{field("legal_name", "Legal name")}{field("code", `${role === "customer" ? "Customer" : "Supplier"} code (auto if blank)`)}<label>Business party type<select name="party_type" defaultValue={initial.party_type ?? role}><option value={role}>{role === "customer" ? "Customer" : "Supplier"}</option><option value="both">Customer & Supplier</option></select></label></fieldset><fieldset><legend>Contact</legend>{field("contact_person", "Contact person")}{field("mobile_number", "Mobile number", "tel")}{field("alternate_mobile", "Alternate mobile", "tel")}{field("email", "Email", "email")}</fieldset><fieldset><legend>Address</legend>{field("address_line1", "Address line 1")}{field("address_line2", "Address line 2")}{field("city", "City")}{field("state", "State")}{field("postal_code", "PIN code")}{field("country", "Country")}</fieldset><fieldset><legend>Tax information</legend><label>GST registration status<select name="gst_status" value={gstStatus} onChange={(event) => setGstStatus(event.target.value as PartyInput["gst_status"])}><option value="unregistered">Unregistered</option><option value="registered">Registered</option><option value="composition">Composition</option><option value="exempt">Exempt</option></select></label>{field("gstin", gstinRequired ? "GSTIN (required)" : "GSTIN", "text", gstinRequired)}{field("pan", "PAN")}</fieldset><fieldset><legend>Commercial information</legend>{field("opening_balance", "Opening balance", "number")}<label>Opening balance type<select name="opening_balance_type" defaultValue={initial.opening_balance_type}><option value="debit">Debit</option><option value="credit">Credit</option></select></label>{field("credit_limit", "Credit limit", "number")}{field("payment_terms_days", "Payment terms (days)", "number")}</fieldset><fieldset><legend>Notes</legend><label className="full-width">Notes<textarea name="notes" defaultValue={initial.notes ?? ""} /></label></fieldset><div className="form-actions"><button type="submit" className="primary-action" disabled={saving}>{saving ? "Saving…" : `Save ${role}`}</button><button type="button" className="secondary-action" onClick={onCancel}>Cancel</button></div></form>;
}
