import { useEffect, useMemo, useState, type FormEvent } from "react";

import type { AccessibleCompany } from "../services/auth";
import { administrationApi, type Bootstrap, type CompanyUser, type Role, type RolePayload, type UserPayload } from "../services/administration";

type Tab = "users" | "roles" | "permissions" | "security";
type Notice = { kind: "success" | "error"; text: string } | null;

const emptyData: Bootstrap = { users: [], roles: [], permissions: [], branches: [], warehouses: [], audit_events: [], effective_permissions: [] };
const nullable = (value: FormDataEntryValue | null) => { const text = String(value ?? "").trim(); return text || null; };

export function UsersRolesPage({ company }: { company?: AccessibleCompany }) {
  const [tab, setTab] = useState<Tab>("users"); const [data, setData] = useState<Bootstrap>(emptyData); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<Notice>(null);
  const [search, setSearch] = useState(""); const [editingUser, setEditingUser] = useState<CompanyUser | null>(null); const [addingUser, setAddingUser] = useState(false); const [editingRole, setEditingRole] = useState<Role | null>(null); const [addingRole, setAddingRole] = useState(false);
  async function reload() { if (!company) return; const next = await administrationApi.bootstrap(company.id); setData(next); }
  useEffect(() => { let active = true; setLoading(true); setNotice(null); setData(emptyData); Promise.resolve(company ? administrationApi.bootstrap(company.id) : emptyData).then((next) => active && setData(next)).catch((error: Error) => active && setNotice({ kind: "error", text: error.message })).finally(() => active && setLoading(false)); return () => { active = false; }; }, [company?.id]);
  const users = useMemo(() => data.users.filter((item) => [item.name, item.email, item.mobile_number, ...item.role_names].join(" ").toLowerCase().includes(search.toLowerCase())), [data.users, search]);
  if (!company) return <section className="organization-empty"><h1>Users &amp; Roles</h1><p>Select an authorized company to manage its users and roles.</p></section>;
  if (loading) return <section className="organization-empty"><h1>Users &amp; Roles</h1><p>Loading the authorized company administration context…</p></section>;
  const successful = async (message: string) => { await reload(); setNotice({ kind: "success", text: message }); };
  return <div className="page-stack administration-page">
    <section className="organization-hero"><div><p className="section-kicker">Company administration</p><h1>Users &amp; Roles</h1><p>Manage company access, role assignments, safe security actions, and permission definitions for {company.business_name}.</p></div><div className="setup-progress"><strong>{data.users.filter((item) => item.company_access_active).length}</strong><span>active company users</span></div></section>
    <nav className="organization-tabs" aria-label="User and role administration"><button className={tab === "users" ? "selected" : ""} onClick={() => setTab("users")}>Users <span>{data.users.length}</span></button><button className={tab === "roles" ? "selected" : ""} onClick={() => setTab("roles")}>Roles <span>{data.roles.length}</span></button><button className={tab === "permissions" ? "selected" : ""} onClick={() => setTab("permissions")}>Permissions <span>{data.permissions.length}</span></button><button className={tab === "security" ? "selected" : ""} onClick={() => setTab("security")}>Security</button></nav>
    {notice && <p className={`notice ${notice.kind}`}>{notice.text}</p>}
    {tab === "users" && <section className="organization-card administration-card"><div className="card-heading"><div><p className="section-kicker">Company-wide access</p><h2>Users</h2><p>Invites use the existing secure activation flow. Default branch and warehouse are preferences, not authorization boundaries.</p></div><button className="primary-action" onClick={() => { setAddingUser(true); setEditingUser(null); }}>Invite user</button></div><div className="admin-toolbar"><input aria-label="Search users" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, contact, or role" /><span>{users.length} shown</span></div>{(addingUser || editingUser) && <UserForm key={editingUser?.id ?? "new"} user={editingUser} data={data} onCancel={() => { setAddingUser(false); setEditingUser(null); }} onSave={async (payload) => { try { if (editingUser) await administrationApi.updateUser(company.id, editingUser.id, payload); else await administrationApi.invite(company.id, payload); await successful(editingUser ? "User access updated." : "Invitation initiated."); setAddingUser(false); setEditingUser(null); } catch (error) { setNotice({ kind: "error", text: (error as Error).message }); } }} />}{!users.length ? <Empty title="No company users found" copy="Invite a person with both email and mobile number to start secure activation." /> : <div className="admin-list">{users.map((user) => <UserRow key={user.id} user={user} onEdit={() => { setEditingUser(user); setAddingUser(false); }} onStatus={async () => { try { await administrationApi.setUserStatus(company.id, user.id, !user.company_access_active); await successful(`User access ${user.company_access_active ? "deactivated" : "activated"}.`); } catch (error) { setNotice({ kind: "error", text: (error as Error).message }); } }} />)}</div>}</section>}
    {tab === "roles" && <section className="organization-card administration-card"><div className="card-heading"><div><p className="section-kicker">Fixed and custom definitions</p><h2>Roles</h2><p>Standard roles are system-managed. Custom roles are company-specific and may only contain permissions the current administrator holds.</p></div><button className="primary-action" onClick={() => { setAddingRole(true); setEditingRole(null); }}>Create custom role</button></div>{(addingRole || editingRole) && <RoleForm key={editingRole?.id ?? "new"} role={editingRole} data={data} onCancel={() => { setAddingRole(false); setEditingRole(null); }} onSave={async (payload) => { try { if (editingRole) await administrationApi.updateRole(company.id, editingRole.id, payload); else await administrationApi.createRole(company.id, payload); await successful(editingRole ? "Custom role updated." : "Custom role created."); setAddingRole(false); setEditingRole(null); } catch (error) { setNotice({ kind: "error", text: (error as Error).message }); } }} />}{<div className="admin-list">{data.roles.map((role) => <article className="admin-row" key={role.id}><div><strong>{role.name}</strong><p>{role.description || "No description."}</p><small>{role.permission_codes.length} permissions · {role.is_system_managed ? "System-managed" : role.is_active ? "Custom active" : "Custom inactive"}</small></div><div className="location-actions">{!role.is_system_managed && <button className="secondary-action" onClick={() => { setEditingRole(role); setAddingRole(false); }}>Edit</button>}<button className="secondary-action" onClick={async () => { const name = window.prompt("Name for the new custom role", `${role.name} copy`); if (!name) return; try { await administrationApi.cloneRole(company.id, role.id, { name, description: role.description, permission_codes: [], is_active: true }); await successful("Role cloned as a custom role."); } catch (error) { setNotice({ kind: "error", text: (error as Error).message }); } }}>Clone</button></div></article>)}</div>}</section>}
    {tab === "permissions" && <section className="organization-card administration-card"><div className="card-heading"><div><p className="section-kicker">Extensible catalogue</p><h2>Permissions</h2><p>Approval rights are separate from routine create and edit rights. Future modules are catalogued only; no transactional workflows are introduced here.</p></div></div><div className="permission-grid">{data.permissions.map((permission) => <article key={permission.code}><strong>{permission.code}</strong><p>{permission.description}</p></article>)}</div></section>}
    {tab === "security" && <section className="organization-card administration-card"><div className="card-heading"><div><p className="section-kicker">Safe administrative controls</p><h2>Security &amp; audit</h2><p>Passwords and token values are never exposed. Reset sends secure P004 instructions; force logout ends regular sessions.</p></div></div><div className="admin-list">{data.users.map((user) => <article className="admin-row" key={user.id}><div><strong>{user.name}</strong><p>{user.account_state} account · email {user.email_verified ? "verified" : "not verified"} · mobile {user.mobile_verified ? "verified" : "not verified"}</p><small>{user.has_active_session ? "An active session exists" : "No active session"}</small></div><div className="location-actions"><button className="secondary-action" onClick={async () => { try { const result = await administrationApi.reset(company.id, user.id); await successful(result.message); } catch (error) { setNotice({ kind: "error", text: (error as Error).message }); } }}>Reset / activation</button><button className="secondary-action" disabled={!user.has_active_session} onClick={async () => { try { const result = await administrationApi.forceLogout(company.id, user.id); await successful(result.message); } catch (error) { setNotice({ kind: "error", text: (error as Error).message }); } }}>Force logout</button></div></article>)}</div><h3 className="audit-heading">Recent administrative events</h3>{!data.audit_events.length ? <Empty title="No administrative events yet" copy="Important P007 administration actions will be recorded here." /> : <div className="audit-list">{data.audit_events.map((event) => <p key={event.id}><strong>{event.action.replaceAll("_", " ")}</strong><span>{new Date(event.created_at).toLocaleString()}</span>{event.details && <small>{event.details}</small>}</p>)}</div>}</section>}
  </div>;
}

function UserRow({ user, onEdit, onStatus }: { user: CompanyUser; onEdit: () => void; onStatus: () => void }) { return <article className="admin-row"><div><strong>{user.name}</strong><p>{user.email} · {user.mobile_number}</p><small>{user.role_names.join(", ") || "No roles"} · {user.account_state} · {user.company_access_active ? "Company access active" : "Company access inactive"}</small></div><div className="location-actions"><button className="secondary-action" onClick={onEdit}>Details</button><button className="secondary-action" onClick={onStatus}>{user.company_access_active ? "Deactivate" : "Activate"}</button></div></article>; }

function UserForm({ user, data, onCancel, onSave }: { user: CompanyUser | null; data: Bootstrap; onCancel: () => void; onSave: (payload: UserPayload) => Promise<void> }) { const [saving, setSaving] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const role_ids = data.roles.filter((role) => form.get(`role-${role.id}`) === "on").map((role) => role.id); await onSave({ name: String(form.get("name") ?? "").trim(), ...(user ? {} : { email: String(form.get("email") ?? "").trim(), mobile_number: String(form.get("mobile_number") ?? "").trim() }), role_ids, default_branch_id: nullable(form.get("default_branch_id")), default_warehouse_id: nullable(form.get("default_warehouse_id")) }); setSaving(false); } return <form className="inline-form admin-form" onSubmit={(event) => void submit(event)}><h3>{user ? "Edit company user" : "Invite company user"}</h3><p className="muted">Email and mobile are required for a new invitation. Credentials are never created or displayed here.</p><fieldset><label>Name<input name="name" defaultValue={user?.name ?? ""} required /></label>{!user && <><label>Email<input name="email" type="email" required /></label><label>Mobile number<input name="mobile_number" required /></label></>}<label>Default branch<select name="default_branch_id" defaultValue={user?.default_branch_id ?? ""}><option value="">No default branch</option>{data.branches.map((item) => <option key={item.id} value={item.id}>{item.name}{item.is_active ? "" : " (inactive)"}</option>)}</select></label><label>Default warehouse<select name="default_warehouse_id" defaultValue={user?.default_warehouse_id ?? ""}><option value="">No default warehouse</option>{data.warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}{item.is_active ? "" : " (inactive)"}</option>)}</select></label></fieldset><fieldset><legend>Company-wide role assignments</legend><div className="checkbox-grid">{data.roles.filter((role) => role.name !== "Owner").map((role) => <label key={role.id} className="checkbox"><input type="checkbox" name={`role-${role.id}`} defaultChecked={user?.role_ids.includes(role.id)} disabled={!role.is_active} />{role.name}</label>)}</div></fieldset><div className="form-actions"><button className="primary-action" disabled={saving}>{saving ? "Saving…" : user ? "Save user" : "Send invitation"}</button><button type="button" className="secondary-action" onClick={onCancel}>Cancel</button></div></form>; }

function RoleForm({ role, data, onCancel, onSave }: { role: Role | null; data: Bootstrap; onCancel: () => void; onSave: (payload: RolePayload) => Promise<void> }) { const [saving, setSaving] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); await onSave({ name: String(form.get("name") ?? "").trim(), description: nullable(form.get("description")), permission_codes: data.permissions.filter((permission) => form.get(`permission-${permission.code}`) === "on").map((permission) => permission.code), is_active: form.get("is_active") === "on" }); setSaving(false); } return <form className="inline-form admin-form" onSubmit={(event) => void submit(event)}><h3>{role ? "Edit custom role" : "New custom role"}</h3><fieldset><label>Name<input name="name" defaultValue={role?.name ?? ""} required /></label><label>Description<input name="description" defaultValue={role?.description ?? ""} /></label><label className="checkbox"><input name="is_active" type="checkbox" defaultChecked={role?.is_active ?? true} />Active</label></fieldset><fieldset><legend>Permissions</legend><div className="checkbox-grid">{data.permissions.map((permission) => <label className="checkbox" key={permission.code} title={permission.description ?? undefined}><input type="checkbox" name={`permission-${permission.code}`} defaultChecked={role?.permission_codes.includes(permission.code)} />{permission.code}</label>)}</div></fieldset><div className="form-actions"><button className="primary-action" disabled={saving}>{saving ? "Saving…" : "Save custom role"}</button><button type="button" className="secondary-action" onClick={onCancel}>Cancel</button></div></form>; }
function Empty({ title, copy }: { title: string; copy: string }) { return <div className="empty-state"><strong>{title}</strong><p>{copy}</p></div>; }
