import type { AccessibleCompany } from "./auth";
import { apiErrorMessage } from "./api";
import { apiBaseUrl as base } from "../config/api";
export type Category={id:string;name:string;code:string|null;description:string|null;is_active:boolean};
export type Item={id:string;name:string;display_name:string|null;code:string;item_type:"goods"|"service";category_id:string|null;category_name:string|null;uom_code:string;hsn_sac_code:string|null;barcode:string|null;purchase_price:number|null;selling_price:number|null;gst_rate:number|null;track_inventory:boolean;opening_stock:number;reorder_level:number|null;default_warehouse_id:string|null;image_url:string|null;notes:string|null;is_active:boolean;description:string|null};
export type ItemInput=Omit<Item,"id"|"code"|"category_name"|"is_active">&{code?:string|null};
async function request<T>(path:string,company:string,method="GET",body?:object):Promise<T>{const res=await fetch(base+path,{method,credentials:"include",headers:{"X-Company-ID":company,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});const payload=await res.json().catch(()=>({}));if(!res.ok)throw new Error(apiErrorMessage(payload,"Item data could not be updated."));return payload as T}
export const itemsApi={items:(company:string,params:Record<string,string>={})=>request<Item[]>(`/items${Object.keys(params).length?"?"+new URLSearchParams(params):""}`,company),categories:(company:string)=>request<Category[]>("/items/categories",company),uoms:(company:string)=>request<string[]>("/items/uoms",company),create:(company:string,payload:ItemInput)=>request<Item>("/items",company,"POST",payload),update:(company:string,id:string,payload:ItemInput)=>request<Item>(`/items/${id}`,company,"PUT",payload),status:(company:string,id:string,is_active:boolean)=>request<Item>(`/items/${id}/status`,company,"PATCH",{is_active}),createCategory:(company:string,payload:Omit<Category,"id"|"is_active">)=>request<Category>("/items/categories",company,"POST",payload),categoryStatus:(company:string,id:string,is_active:boolean)=>request<Category>(`/items/categories/${id}/status`,company,"PATCH",{is_active})};
export const companyName=(company?:AccessibleCompany)=>company?.business_name??"your company";
