"""P010 purchase management foundations.

Revision ID: g010a1b2c3d4
Revises: f009a1b2c3d4
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "g010a1b2c3d4"
down_revision = "f009a1b2c3d4"
branch_labels = None
depends_on = None

uid = postgresql.UUID(as_uuid=True)
timestamps = [sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))]
totals = [sa.Column("subtotal", sa.Numeric(14,2), nullable=False, server_default="0"), sa.Column("discount_total", sa.Numeric(14,2), nullable=False, server_default="0"), sa.Column("tax_total", sa.Numeric(14,2), nullable=False, server_default="0"), sa.Column("round_off", sa.Numeric(14,2), nullable=False, server_default="0"), sa.Column("grand_total", sa.Numeric(14,2), nullable=False, server_default="0")]

def commercial_lines(table, parent):
    parent_table = {"purchase_order_id": "purchase_orders", "purchase_invoice_id": "purchase_invoices"}[parent]
    op.create_table(table, sa.Column("id",uid,primary_key=True), sa.Column(parent,uid,sa.ForeignKey(parent_table + ".id",ondelete="CASCADE"),nullable=False), sa.Column("item_id",uid,sa.ForeignKey("items.id",ondelete="RESTRICT"),nullable=False), sa.Column("item_name",sa.String(255),nullable=False), sa.Column("item_code",sa.String(64),nullable=False), sa.Column("description",sa.Text()), sa.Column("uom_code",sa.String(16),nullable=False), sa.Column("quantity",sa.Numeric(14,3),nullable=False), sa.Column("unit_rate",sa.Numeric(14,2),nullable=False), sa.Column("discount_percent",sa.Numeric(5,2),nullable=False,server_default="0"), sa.Column("gst_rate",sa.Numeric(5,2)), sa.Column("base_amount",sa.Numeric(14,2),nullable=False),sa.Column("discount_amount",sa.Numeric(14,2),nullable=False),sa.Column("tax_amount",sa.Numeric(14,2),nullable=False),sa.Column("line_total",sa.Numeric(14,2),nullable=False),sa.CheckConstraint("quantity > 0",name=table+"_quantity"),sa.CheckConstraint("unit_rate >= 0",name=table+"_rate"),sa.CheckConstraint("discount_percent >= 0 AND discount_percent <= 100",name=table+"_discount"))
    op.create_index("ix_"+table+"_"+parent,table,[parent])

def upgrade():
    op.create_table("purchase_document_sequences",sa.Column("id",uid,primary_key=True),sa.Column("company_id",uid,sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("document_type",sa.String(16),nullable=False),sa.Column("next_value",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("company_id","document_type",name="purchase_document_sequence_company_type")); op.create_index("ix_purchase_document_sequences_company_id","purchase_document_sequences",["company_id"])
    op.create_table("purchase_orders",sa.Column("id",uid,primary_key=True),sa.Column("company_id",uid,sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("supplier_id",uid,sa.ForeignKey("parties.id",ondelete="RESTRICT"),nullable=False),sa.Column("branch_id",uid,sa.ForeignKey("branches.id",ondelete="RESTRICT")),sa.Column("warehouse_id",uid,sa.ForeignKey("warehouses.id",ondelete="RESTRICT")),sa.Column("number",sa.String(64),nullable=False),sa.Column("order_date",sa.Date(),nullable=False),sa.Column("expected_delivery_date",sa.Date()),sa.Column("supplier_reference",sa.String(128)),sa.Column("payment_terms",sa.String(255)),sa.Column("notes",sa.Text()),sa.Column("terms_conditions",sa.Text()),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),*totals,*timestamps,sa.CheckConstraint("status IN ('draft','submitted','approved','partially_received','received','cancelled')",name="purchase_order_status")); op.create_index("ix_purchase_orders_company_id","purchase_orders",["company_id"]);op.create_index("ix_purchase_orders_supplier_id","purchase_orders",["supplier_id"]);op.create_index("uq_purchase_order_number","purchase_orders",["company_id","number"],unique=True)
    op.create_table("goods_receipts",sa.Column("id",uid,primary_key=True),sa.Column("company_id",uid,sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("supplier_id",uid,sa.ForeignKey("parties.id",ondelete="RESTRICT"),nullable=False),sa.Column("purchase_order_id",uid,sa.ForeignKey("purchase_orders.id",ondelete="RESTRICT")),sa.Column("warehouse_id",uid,sa.ForeignKey("warehouses.id",ondelete="RESTRICT")),sa.Column("number",sa.String(64),nullable=False),sa.Column("receipt_date",sa.Date(),nullable=False),sa.Column("supplier_challan_reference",sa.String(128)),sa.Column("notes",sa.Text()),sa.Column("status",sa.String(16),nullable=False,server_default="received"),*timestamps,sa.CheckConstraint("status IN ('draft','received','cancelled')",name="goods_receipt_status"));op.create_index("ix_goods_receipts_company_id","goods_receipts",["company_id"]);op.create_index("ix_goods_receipts_supplier_id","goods_receipts",["supplier_id"]);op.create_index("uq_goods_receipt_number","goods_receipts",["company_id","number"],unique=True)
    op.create_table("purchase_invoices",sa.Column("id",uid,primary_key=True),sa.Column("company_id",uid,sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("supplier_id",uid,sa.ForeignKey("parties.id",ondelete="RESTRICT"),nullable=False),sa.Column("purchase_order_id",uid,sa.ForeignKey("purchase_orders.id",ondelete="RESTRICT")),sa.Column("goods_receipt_id",uid,sa.ForeignKey("goods_receipts.id",ondelete="RESTRICT")),sa.Column("number",sa.String(64),nullable=False),sa.Column("supplier_invoice_number",sa.String(128),nullable=False),sa.Column("supplier_invoice_date",sa.Date(),nullable=False),sa.Column("document_date",sa.Date(),nullable=False),sa.Column("due_date",sa.Date()),sa.Column("payment_terms",sa.String(255)),sa.Column("notes",sa.Text()),sa.Column("status",sa.String(16),nullable=False,server_default="draft"),*totals,*timestamps,sa.CheckConstraint("status IN ('draft','approved','cancelled')",name="purchase_invoice_status"));op.create_index("ix_purchase_invoices_company_id","purchase_invoices",["company_id"]);op.create_index("ix_purchase_invoices_supplier_id","purchase_invoices",["supplier_id"]);op.create_index("uq_purchase_invoice_number","purchase_invoices",["company_id","number"],unique=True);op.create_index("uq_supplier_invoice_reference","purchase_invoices",["company_id","supplier_id","supplier_invoice_number"],unique=True)
    commercial_lines("purchase_order_lines","purchase_order_id"); commercial_lines("purchase_invoice_lines","purchase_invoice_id")
    op.create_table("goods_receipt_lines",sa.Column("id",uid,primary_key=True),sa.Column("goods_receipt_id",uid,sa.ForeignKey("goods_receipts.id",ondelete="CASCADE"),nullable=False),sa.Column("purchase_order_line_id",uid,sa.ForeignKey("purchase_order_lines.id",ondelete="RESTRICT")),sa.Column("item_id",uid,sa.ForeignKey("items.id",ondelete="RESTRICT"),nullable=False),sa.Column("item_name",sa.String(255),nullable=False),sa.Column("item_code",sa.String(64),nullable=False),sa.Column("uom_code",sa.String(16),nullable=False),sa.Column("ordered_quantity",sa.Numeric(14,3)),sa.Column("received_quantity",sa.Numeric(14,3),nullable=False),sa.Column("accepted_quantity",sa.Numeric(14,3),nullable=False),sa.Column("rejected_quantity",sa.Numeric(14,3),nullable=False,server_default="0"),sa.Column("remarks",sa.Text()),sa.CheckConstraint("received_quantity > 0",name="goods_receipt_line_received"),sa.CheckConstraint("accepted_quantity >= 0",name="goods_receipt_line_accepted"),sa.CheckConstraint("rejected_quantity >= 0",name="goods_receipt_line_rejected"));op.create_index("ix_goods_receipt_lines_goods_receipt_id","goods_receipt_lines",["goods_receipt_id"])

def downgrade():
    for table in ("goods_receipt_lines","purchase_invoice_lines","purchase_order_lines","purchase_invoices","goods_receipts","purchase_orders","purchase_document_sequences"): op.drop_table(table)
